### ISSUE TITLE
make url validator

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/garvis#77]

**Comment by tianhaoz95** [comment]
```my-block
test: test
what: this
```

**Comment by tianhaoz95** [comment]
```yml
garvis: true
fix: #76 
depend:
 - #64 
 - #72 
```
